### ISSUE TITLE
orthosnap: error: unrecognized arguments: -ip median_seq_len

### ISSUE THREAD

**Issue by alexvasilikop** [JLSteenwyk/orthosnap#2]
Hello,

I am trying to invoke the option for in-paralog selection but it seems it is not recognized

$ orthosnap -f OG0000452.fa -t OG0000452_tree.txt -ip median_seq_len

orthosnap: error: unrecognized arguments: -ip median_seq_len

Also in the $orthosnap -h command there is no such option but it exists in the documentation
$orthosnap -h

           _   _                                 
           | | | |                                
  ___  _ __| |_| |__   ___  ___ _ __   __ _ _ __  
 / _ \| '__| __| '_ \ / _ \/ __| '_ \ / _` | '_ \ 
| (_) | |  | |_| | | | (_) \__ \ | | | (_| | |_) |
 \___/|_|   \__|_| |_|\___/|___/_| |_|\__,_| .__/ 
                                           | |    
                                           |_|     

 Version: 0.0.1
 Citation: Steenwyk et al.
 Usage: orthosnap <input> [optional arguments]

required arguments:
  -t, --tree <newick tree file>
      input tree file in newick format
  
  -f, --fasta <fasta file>
      input sequence file in fasta format                 

optional arguments:
  -s, --support  <support>
      support threshold for bipartition collapsing
      default: 80
  
  -o, --occupancy  <occupancy>
      occupancy threshold for minimum number of tips in orthologous subgroup
      default: 50 percent of total number of taxa  
  
  
  -------------------------------------
Detailed explanation of arguments | 
  -------------------------------------
  -t, --tree <newick tree file>
      - input tree file in newick format
      - taxa name and gene name should be separate by a "|" symbol
        For example, "gene_a" from "species_a" should appear in the
        tree as "species_a|gene_a", and "gene_b" from "species_a"
        should appear in the tree as "species_a|gene_b", and so 
        on and so forth.
  
  -f, --fasta <fasta file>
      - input sequence file in fasta format 
      - taxa name and gene name should be formatted the same as in
        the tree file. Thus, "gene_a" from "species_a" should appear
        in the tree as "species_a|gene_a" and so on and so forth.
  
  -s, --support  <support>
      - support threshold for bipartition collapsing
      - all bipartitions will values less than the specified value 
        will be collapsed. For example, if the support threshold
        value is 80, all bipartitions with 79 or less support
        will be collapsed.
      - default value is 80 and is set for ultrafast bootstrap
        approximations. If bipartitions support was evaluated 
        using standard bootstrap, a common threshold to use is 70.
  
  -o, --occupancy  <occupancy>
      - occupancy threshold for minimum number of tips in orthologous
        subgroup. 
      - default value is 50 percent of the total number of taxa
      - values are rounded to the nearest integer. For example,
        if there are 15 taxa, the occupancy threshold will be 8.

What might be the issue?
Thanks
Alex

**Comment by JLSteenwyk** [comment]
Hi Alex,

First, thank you very much for checking out OrthoSNAP and for providing a comment. OrthoSNAP and other software would be nothing without a helpful user base—i.e., researchers like you!

Second, the issue stems from what version of OrthoSNAP you are using. The `-ip` argument was not added until a later version of OrthoSNAP. A changelog of OrthoSNAP is available here: [changelog, docs](https://jlsteenwyk.com/orthosnap/change_log/index.html). To update your version of OrthoSNAP, you can use the following command: `pip install orthosnap -U`.

Thanks again for using OrthoSNAP. You may find some of the other software I have developed useful for your research; here is the link in case you are interested :D [https://jlsteenwyk.com/software.html](https://jlsteenwyk.com/software.html).

best,

Jacob
