### ISSUE TITLE
only identify one SNAP-OG

### ISSUE THREAD

**Issue by XXboop** [JLSteenwyk/orthosnap#5]
Dear Jacob
I used orthofinder for gene family clustering of five species (Ab, Ad, Ak, As, Lo). Then I would like to use orthoSNAP with default parameter to classify multi-copy gene families. But there are many gene families whose trees actually have multiple clades. But orthoSNAp can only identify one SNAP-OG. For example, the following gene families.  orthoSNAP identified only one SNAP-OG, including Ab|AB06G03741-RB, Lo|LO08G03008-RA, As|AS05G03226-RB. But why wasn't the other clade identified as SNAP-OG？Can another clade be a SNAP-OG？

((Ab|AB06G03741-RB:0.0993161,(As|AS05G03226-RB:0.0364093,(Lo|LO08G03008-RA:0.0337749,Lo|LO08G03009-RA:0.0289553)0.996:0.0172954)0.992:0.0215731)1:0.0494888,((Lo|LO08G03007-RB:0.0387437,(As|AS05G03228-RB:0.0205169,As|AS05G03236-RA:0.0262063)0.897:0.0062029)1:0.157462,((Ad|AD03G00060-RA:0.0339494,(Ad|AD03G00059-RA:0.0129773,((Ad|AD08G00004-RA:0.0885369,Ad|AD08G00001-RC:5e-09)0:6e-09,Ad|AD08G00003-RA:0.0236448)0.763:0.00254957)0.632:0.00239112)0.912:0.0083526,(Ab|AB06G01323-RA:0.00687747,(Ab|AB06G01309-RA:0.00290853,Ak|AK09G04755-RB:0.00193846)0.734:0.0009175)0.991:0.0153459)1:0.267442)1:0.0494888);

![image](https://github.com/JLSteenwyk/orthosnap/assets/84905582/47d498bc-099f-442e-80b8-bd764ca0aade)

Best regards
Xiaoxu

**Comment by JLSteenwyk** [comment]
Hi Xiaoxu, 

I hope you are doing well.

You are only getting one SNAP-OG because the genes in the green box do not constitute a proper SNAP-OG. This is in part due to the relationship between the two Ab paralogs and Ak.

Hope this helps!

best,

Jacob

**Comment by XXboop** [comment]
Dear Jacob

Thank you for your reply. Is the clade in the green box not a SNAP-OG because Ab|AB06G01309 and Ak|AK09G04755 are clustered together,not Ab|AB06G01323. But bootstrap value of Ab|AB06G01309 and Ak|AK09G04755 is only 0.734?  Can the clade in the green box become a SNAP-OG by adjusting orthosnap parameters? I did not change the results of orthoSNAP by adjusting the -s and -o.

best regards
Xiaoxu

**Comment by JLSteenwyk** [comment]
You can get two SNAP-OGs from that tree. 

I would recommend changing the -s parameter from the default, which is 80, to something like 0.7.

Also, please make sure you are using the latest release, version 1.0.0.
