### ISSUE TITLE
Snakemake environment build-up for orthosnap.

### ISSUE THREAD

**Issue by Andyargueasae** [JLSteenwyk/orthosnap#7]
Hi,

I am trying to use orthosnap as one part of the snakemake workflow to work out the phylogeny. My colleague built up the conda environment for orthosnap like this:
<img width="612" alt="image" src="https://github.com/JLSteenwyk/orthosnap/assets/88032525/95c6bc74-4008-4576-9341-00d78dae666c">

But seems that for some packages especially biopython and tqdm, there is conflict between them. So I wonder for orthosnap, which dependencies are essential that I could keep them?

Sorry for bothering

**Comment by JLSteenwyk** [comment]
Hi @Andyargueasae,

Thank you so much for choosing OrthoSNAP for your Snakemake workflow. 

See here for a YAML file that addresses your need. https://github.com/rbturnbull/orthoflow/blob/master/orthoflow/workflow/envs/orthosnap.yaml

thanks again!
